# Generated by Django 5.0.4 on 2024-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('started', 'Started'), ('delayed', 'Delayed'), ('ended', 'Ended')], default='pending', max_length=10),
        ),
    ]
