# Generated by Django 5.0.4 on 2024-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_department_profile_group_profile_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
