# Generated by Django 5.0.4 on 2024-05-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='bicho1@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
