# Generated by Django 5.0.4 on 2024-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_manager_membership_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='position',
            field=models.CharField(default='MEMBER', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], default='PENDING', max_length=100),
        ),
    ]
