# Generated by Django 5.0.4 on 2024-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_membership_position_alter_membership_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logo'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('REMOVED', 'Removed'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active')], default='PENDING', max_length=100),
        ),
    ]
