# Generated by Django 5.0.4 on 2024-05-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_club_logo_alter_membership_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REMOVED', 'Removed')], default='PENDING', max_length=100),
        ),
    ]
